version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pedroomr-wireshark_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
    networks:
      - app_net

  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data:/config
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - app_net

networks:
  app_net:
