version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pedroomr-wireshark_1
      APP_PORT: 3001
      PROXY_AUTH_ADD: "false"

  wireshark:
    image: lscr.io/linuxserver/wireshark:latest
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: unless-stopped