version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pedroomr-wireshark_app_1
      APP_PORT: 3001
      PROXY_AUTH_ADD: "false"

  app:
    image: lscr.io/linuxserver/wireshark:latest
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - ${UMBREL_ROOT}/data/storage/wireshark:/umbrel
    restart: unless-stopped
