version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: pedroomr-xampp_1
      APP_PORT: 41062
      PROXY_AUTH_ADD: "false"

  xampp:
    image: tomsik68/xampp
    restart: on-failure
    volumes:
      - ${UMBREL_ROOT}/data/storage/htdocs:/opt/lampp/htdocs:rw
    ports:
      - "41062:80"
    environment: {}
    init: true