version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: pedroomr-xampp_app_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  app:
    image: tomsik68/xampp
    restart: on-failure
    init: true
    volumes:
      - ${UMBREL_ROOT}/data/storage/htdocs:/opt/lampp/htdocs:rw