version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: pedroomr-dockur-windows-xp_windows_1
      APP_PORT: 8006
      PROXY_AUTH_ADD: "false"

  windows:
    image: dockurr/windows
    restart: on-failure
    environment:
      VERSION: "11"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Lisbon
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ${APP_DATA_DIR}/data:/storage:rw
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    user: "1000:1000"
    init: true
